services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: storagesystem:server
    ports:
      - "5505:5505"
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
  
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: storagesystem:app
    ports:
      - "5506:5506"
    restart: unless-stopped
